name: Build New App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - macos-latest
          - ubuntu-latest
      url:
        description: Url (required)
        required: true
      name:
        description: Name (required)
        required: true
      icon_url:
        description: Url to icon file
        required: false
      # height:
      #   description: Height
      #   required: false
      #   default: "780"
      # width:
      #   description: Width
      #   required: false
      #   default: "1200"
      # hide_title_bar:
      #   description: Hide title bar (macOS)
      #   required: false
      #   type: boolean
      #   default: false
      # fullscreen:
      #   description: Fullscreen
      #   required: false
      #   type: boolean
      #   default: false
      # activation_shortcut:
      #   description: Activation shortcut
      #   required: false
      #   default: ""
      # always_on_top:
      #   description: Always on top
      #   required: false
      #   type: boolean
      #   default: false
      app_version:
        description: App version
        required: false
        default: "1.0.0"
      # dark_mode:
      #   description: Dark mode
      #   required: false
      #   type: boolean
      #   default: false
      # disabled_web_shortcuts:
      #   description: Disabled web shortcuts
      #   required: false
      #   type: boolean
      #   default: false
      # multi_arch:
      #   description: Multi arch, (macOS)
      #   required: false
      #   type: boolean
      #   default: false
      # targets:
      #   description: Targets (Linux)
      #   required: false
      #   default: deb
      #   type: choice
      #   options:
      #     - deb
      #     - appimage
      #     - rpm
      # user_agent:
      #   description: User agent
      #   required: false
      #   default: ""
      # show_system_tray:
      #   description: Show system tray
      #   required: false
      #   type: boolean
      #   default: false
      # system_tray_icon_url:
      #   description: Url to system tray icon file
      #   required: false
      #   default: ""
      # installer_language:
      #   description: Installer language (Windows)
      #   required: false
      #   default: en-US
      # inject_url:
      #   description: Url to inject file
      #   required: false
      #   default: ""
      # proxy_url:
      #   description: Proxy url
      #   required: false
      #   default: ""
      # debug:
      #   description: Debug
      #   required: false
      #   type: boolean
      #   default: false
      more_options:
        description: More options (query string format)
        required: false
        default: ""

jobs:
  build:
    name: ${{ inputs.platform }}
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Rust for ubuntu
        if: inputs.platform == 'ubuntu-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Install Rust for windows
        if: inputs.platform == 'windows-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-msvc
          target: x86_64-pc-windows-msvc

      - name: Install Rust for macos
        if: inputs.platform == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Install dependencies (ubuntu only)
        if: inputs.platform == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev gnome-video-effects gnome-video-effects-extra
          version: 1.1

      - name: Install dependencies
        run: pnpm install

      - name: Rust cache restore
        uses: actions/cache/restore@v4
        id: cache_store
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            node_modules/pake-cli/src-tauri/target/
          key: ${{ inputs.platform }}-cargo-${{ hashFiles('node_modules/pake-cli/src-tauri/Cargo.lock') }}

      - name: Build app
        run: pnpm run build
        env:
          URL: ${{ inputs.url }}
          NAME: ${{ inputs.name }}
          ICON_URL: ${{ inputs.icon_url }}
          APP_VERSION: ${{ inputs.app_version }}
          MORE_OPTIONS: ${{ inputs.more_options }}

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ inputs.platform }}.zip
          path: output/*

      - name: Rust cache store
        uses: actions/cache/save@v4
        if: steps.cache_store.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            node_modules/pake-cli/src-tauri/target/
          key: ${{ inputs.platform }}-cargo-${{ hashFiles('node_modules/pake-cli/src-tauri/Cargo.lock') }}
